upstream backend_upstream {
  server backend:5000;
}

server {
  listen 80;

  location / {
    root /usr/share/nginx/html;
    index index.html index.htm;
    try_files $uri $uri/ /index.html;
  }

  location /create {
    proxy_pass http://backend_upstream;
    proxy_set_header Host $host;
  }

  location /guess/ {
    proxy_pass http://backend_upstream;
    proxy_set_header Host $host;
  }
}